name: pr
on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # build all assets for CI context
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npx tsc --version
      - run: npm run lint
      - run: npm run build

  # dry run for releasability, does everything **except** the actual npm publish
  release-dry-run:
    uses: ./.github/workflows/release-channel.yml
    with:
      tag: v2.7.0
      channel: canary
      dry_run: true
