on:
  push:
    branches:
      - master
permissions:
  contents: write
  pull-requests: write
name: release-please-canary

jobs:
  release-please-canary:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: config/release-please-canary-config.json
          manifest-file: config/.release-please-canary-manifest.json
