on: workflow_dispatch
permissions:
  contents: write
  pull-requests: write
name: release-please-stable

jobs:
  release-please-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: config/release-please-stable-config.json
          manifest-file: config/.release-please-stable-manifest.json
